<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="Pacific Standard Time">
<General productName="HP Unified Functional Testing" productVer="11.50" os="Windows 7" host="VDI-MCSV2-14"><DocLocation><![CDATA[C:\Users\pkrishna\Desktop\Automate\TestDriver]]></DocLocation></General>
<Doc rID="T1"   productName= "HP Unified Functional Testing"  >
<DName><![CDATA[TestDriver]]></DName>
<Res><![CDATA[Res3]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<Action rID="T3">
<AName><![CDATA[Action1]]></AName>
<Step rID="T4">
<Obj plainTxt="False" ><![CDATA[Pb_wdwSAA]]></Obj>
<Details plainTxt="False" ><![CDATA[PbWindow]]></Details>
<Time><![CDATA[4/29/2015 - 0:06:32]]></Time>
<TimeTick>1430291192</TimeTick>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[Pb_wdwSAA.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[4/29/2015 - 0:06:32]]></Time>
<TimeTick>1430291192</TimeTick>
<NodeArgs eType="Replay" icon="4" nRep="8" >
<Disp><![CDATA[Pb_wdwSAA.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[Pb_wdwSAA.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[4/29/2015 - 0:06:32]]></Time>
<TimeTick>1430291192</TimeTick>
<NodeArgs eType="Replay" icon="4" nRep="9" >
<Disp><![CDATA[Pb_wdwSAA.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="4" nRep="7" >
<Disp><![CDATA[Pb_wdwSAA]]></Disp>
</NodeArgs>
</Step>
<Step rID="T7">
<Obj ><![CDATA[<font color="green">User should be navigated to SAA window</font>]]></Obj>
<Details ><![CDATA[<font color="green">User is navigated to SAA window</font>]]></Details>
<Time><![CDATA[4/29/2015 - 0:06:32]]></Time>
<TimeTick>1430291192</TimeTick>
<NodeArgs eType="User" icon="5" nRep="10" status="Passed" >
<Disp><![CDATA[<font color="green">User should be navigated to SAA window</font>]]></Disp>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[Pb_wdwSAA]]></Obj>
<Details plainTxt="False" ><![CDATA[PbWindow]]></Details>
<Time><![CDATA[4/29/2015 - 0:06:32]]></Time>
<TimeTick>1430291192</TimeTick>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[Menu.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["&ltItem 6&gt;&ltItem 1&gt"]]></Details>
<Time><![CDATA[4/29/2015 - 0:06:32]]></Time>
<TimeTick>1430291192</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="13" >
<Disp><![CDATA[Menu.Select]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="4" nRep="12" >
<Disp><![CDATA[Pb_wdwSAA]]></Disp>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj ><![CDATA[Select the Select Profile Submenu from Codes Menu]]></Obj>
<Details ><![CDATA[The SubMenu Value<font color="blue"><b><i> Item 1 </i></b></font> is selected successfully from Menu Tab<font color="blue"><b><i> Item 6 </i></b></font> in the Window]]></Details>
<Time><![CDATA[4/29/2015 - 0:06:33]]></Time>
<TimeTick>1430291193</TimeTick>
<NodeArgs eType="User" icon="5" nRep="14" >
<Disp><![CDATA[Select the Select Profile Submenu from Codes Menu]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[Pb_wdwSAA]]></Obj>
<Details plainTxt="False" ><![CDATA[PbWindow]]></Details>
<Time><![CDATA[4/29/2015 - 0:06:36]]></Time>
<TimeTick>1430291196</TimeTick>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[Pb_wdwSelectProfile.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[4/29/2015 - 0:06:36]]></Time>
<TimeTick>1430291196</TimeTick>
<NodeArgs eType="Replay" icon="4" nRep="19" >
<Disp><![CDATA[Pb_wdwSelectProfile.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[Pb_wdwSelectProfile.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[4/29/2015 - 0:06:39]]></Time>
<TimeTick>1430291199</TimeTick>
<NodeArgs eType="Replay" icon="4" nRep="23" >
<Disp><![CDATA[Pb_wdwSelectProfile.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[Pb_wdwSelectProfile.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[4/29/2015 - 0:06:41]]></Time>
<TimeTick>1430291201</TimeTick>
<NodeArgs eType="Replay" icon="4" nRep="24" >
<Disp><![CDATA[Pb_wdwSelectProfile.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[Pb_wdwSelectProfile.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[4/29/2015 - 0:06:41]]></Time>
<TimeTick>1430291201</TimeTick>
<NodeArgs eType="Replay" icon="4" nRep="25" >
<Disp><![CDATA[Pb_wdwSelectProfile.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="4" nRep="18" >
<Disp><![CDATA[Pb_wdwSAA]]></Disp>
</NodeArgs>
</Step>
<Step rID="T16">
<Obj ><![CDATA[<font color="green">User should be navigated to Select Profile window</font>]]></Obj>
<Details ><![CDATA[<font color="green">User is navigated to w_mcs_saa_select_profile window</font>]]></Details>
<Time><![CDATA[4/29/2015 - 0:06:41]]></Time>
<TimeTick>1430291201</TimeTick>
<NodeArgs eType="User" icon="5" nRep="26" status="Passed" >
<Disp><![CDATA[<font color="green">User should be navigated to Select Profile window</font>]]></Disp>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[Pb_wdwSAA]]></Obj>
<Details plainTxt="False" ><![CDATA[PbWindow]]></Details>
<Time><![CDATA[4/29/2015 - 0:06:43]]></Time>
<TimeTick>1430291203</TimeTick>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[Pb_wdwSelectProfile]]></Obj>
<Details plainTxt="False" ><![CDATA[PbWindow]]></Details>
<Time><![CDATA[4/29/2015 - 0:06:43]]></Time>
<TimeTick>1430291203</TimeTick>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[Pb_lstSelectProfile.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[4/29/2015 - 0:06:43]]></Time>
<TimeTick>1430291203</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="29" >
<Disp><![CDATA[Pb_lstSelectProfile.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[Pb_lstSelectProfile.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Account Executive Profile"]]></Details>
<Time><![CDATA[4/29/2015 - 0:06:43]]></Time>
<TimeTick>1430291203</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="31" >
<Disp><![CDATA[Pb_lstSelectProfile.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[Pb_lstSelectProfile.Activate]]></Obj>
<Details plainTxt="False" ><![CDATA["Account Executive Profile"]]></Details>
<Time><![CDATA[4/29/2015 - 0:06:43]]></Time>
<TimeTick>1430291203</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="33" >
<Disp><![CDATA[Pb_lstSelectProfile.Activate]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="4" nRep="28" >
<Disp><![CDATA[Pb_wdwSelectProfile]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="4" nRep="27" >
<Disp><![CDATA[Pb_wdwSAA]]></Disp>
</NodeArgs>
</Step>
<Step rID="T22">
<Obj ><![CDATA[Select profile of user from Profile list]]></Obj>
<Details ><![CDATA[The value: <font color="blue"><b><i>Account Executive Profile</i></b></font> is selected from the Dropdown <b>lstSelectProfile</b>]]></Details>
<Time><![CDATA[4/29/2015 - 0:06:44]]></Time>
<TimeTick>1430291204</TimeTick>
<NodeArgs eType="User" icon="5" nRep="34" >
<Disp><![CDATA[Select profile of user from Profile list]]></Disp>
</NodeArgs>
</Step>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[Pb_wdwSAA]]></Obj>
<Details plainTxt="False" ><![CDATA[PbWindow]]></Details>
<Time><![CDATA[4/29/2015 - 0:06:47]]></Time>
<TimeTick>1430291207</TimeTick>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[Pb_wdwAccountExecutiveProfile.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[4/29/2015 - 0:06:47]]></Time>
<TimeTick>1430291207</TimeTick>
<NodeArgs eType="Replay" icon="4" nRep="39" >
<Disp><![CDATA[Pb_wdwAccountExecutiveProfile.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[Pb_wdwAccountExecutiveProfile.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[4/29/2015 - 0:06:51]]></Time>
<TimeTick>1430291211</TimeTick>
<NodeArgs eType="Replay" icon="4" nRep="43" >
<Disp><![CDATA[Pb_wdwAccountExecutiveProfile.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[Pb_wdwAccountExecutiveProfile.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[4/29/2015 - 0:06:54]]></Time>
<TimeTick>1430291214</TimeTick>
<NodeArgs eType="Replay" icon="4" nRep="47" >
<Disp><![CDATA[Pb_wdwAccountExecutiveProfile.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[Pb_wdwAccountExecutiveProfile.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[4/29/2015 - 0:06:57]]></Time>
<TimeTick>1430291217</TimeTick>
<NodeArgs eType="Replay" icon="4" nRep="51" >
<Disp><![CDATA[Pb_wdwAccountExecutiveProfile.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[Pb_wdwAccountExecutiveProfile.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[4/29/2015 - 0:07:00]]></Time>
<TimeTick>1430291220</TimeTick>
<NodeArgs eType="Replay" icon="4" nRep="55" >
<Disp><![CDATA[Pb_wdwAccountExecutiveProfile.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[Pb_wdwAccountExecutiveProfile.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[4/29/2015 - 0:07:03]]></Time>
<TimeTick>1430291223</TimeTick>
<NodeArgs eType="Replay" icon="4" nRep="59" >
<Disp><![CDATA[Pb_wdwAccountExecutiveProfile.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[Pb_wdwAccountExecutiveProfile.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[4/29/2015 - 0:07:06]]></Time>
<TimeTick>1430291226</TimeTick>
<NodeArgs eType="Replay" icon="4" nRep="63" >
<Disp><![CDATA[Pb_wdwAccountExecutiveProfile.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA[Pb_wdwAccountExecutiveProfile.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[4/29/2015 - 0:07:09]]></Time>
<TimeTick>1430291229</TimeTick>
<NodeArgs eType="Replay" icon="4" nRep="67" >
<Disp><![CDATA[Pb_wdwAccountExecutiveProfile.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[Pb_wdwAccountExecutiveProfile.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[4/29/2015 - 0:07:13]]></Time>
<TimeTick>1430291233</TimeTick>
<NodeArgs eType="Replay" icon="4" nRep="71" >
<Disp><![CDATA[Pb_wdwAccountExecutiveProfile.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T33">
<Obj plainTxt="False" ><![CDATA[Pb_wdwAccountExecutiveProfile.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[4/29/2015 - 0:07:14]]></Time>
<TimeTick>1430291234</TimeTick>
<NodeArgs eType="Replay" icon="4" nRep="72" >
<Disp><![CDATA[Pb_wdwAccountExecutiveProfile.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T34">
<Obj plainTxt="False" ><![CDATA[Pb_wdwAccountExecutiveProfile.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[4/29/2015 - 0:07:14]]></Time>
<TimeTick>1430291234</TimeTick>
<NodeArgs eType="Replay" icon="4" nRep="73" >
<Disp><![CDATA[Pb_wdwAccountExecutiveProfile.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="4" nRep="38" >
<Disp><![CDATA[Pb_wdwSAA]]></Disp>
</NodeArgs>
</Step>
<Step rID="T35">
<Obj ><![CDATA[<font color="green">User should be navigated to Account Executive Profile window</font>]]></Obj>
<Details ><![CDATA[<font color="green">User is navigated to w_mcs_saa_account_executive window</font>]]></Details>
<Time><![CDATA[4/29/2015 - 0:07:14]]></Time>
<TimeTick>1430291234</TimeTick>
<NodeArgs eType="User" icon="5" nRep="74" status="Passed" >
<Disp><![CDATA[<font color="green">User should be navigated to Account Executive Profile window</font>]]></Disp>
</NodeArgs>
</Step>
<Step rID="T36">
<Obj plainTxt="False" ><![CDATA[Pb_wdwSAA]]></Obj>
<Details plainTxt="False" ><![CDATA[PbWindow]]></Details>
<Time><![CDATA[4/29/2015 - 0:07:16]]></Time>
<TimeTick>1430291236</TimeTick>
<Step rID="T37">
<Obj plainTxt="False" ><![CDATA[Pb_wdwAccountExecutiveProfile]]></Obj>
<Details plainTxt="False" ><![CDATA[PbWindow]]></Details>
<Time><![CDATA[4/29/2015 - 0:07:16]]></Time>
<TimeTick>1430291236</TimeTick>
<Step rID="T38">
<Obj plainTxt="False" ><![CDATA[Pb_btnNew.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[4/29/2015 - 0:07:16]]></Time>
<TimeTick>1430291236</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="77" >
<Disp><![CDATA[Pb_btnNew.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T39">
<Obj plainTxt="False" ><![CDATA[Pb_btnNew.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[4/29/2015 - 0:07:17]]></Time>
<TimeTick>1430291237</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="79" >
<Disp><![CDATA[Pb_btnNew.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="4" nRep="76" >
<Disp><![CDATA[Pb_wdwAccountExecutiveProfile]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="4" nRep="75" >
<Disp><![CDATA[Pb_wdwSAA]]></Disp>
</NodeArgs>
</Step>
<Step rID="T40">
<Obj ><![CDATA[Click on New button]]></Obj>
<Details ><![CDATA[The Button: <b>btnNew</b> is clicked successfully]]></Details>
<Time><![CDATA[4/29/2015 - 0:07:17]]></Time>
<TimeTick>1430291237</TimeTick>
<NodeArgs eType="User" icon="5" nRep="80" >
<Disp><![CDATA[Click on New button]]></Disp>
</NodeArgs>
</Step>
<Step rID="T41">
<Obj plainTxt="False" ><![CDATA[Pb_wdwSAA]]></Obj>
<Details plainTxt="False" ><![CDATA[PbWindow]]></Details>
<Time><![CDATA[4/29/2015 - 0:07:19]]></Time>
<TimeTick>1430291239</TimeTick>
<Step rID="T42">
<Obj plainTxt="False" ><![CDATA[Pb_wdwAccountExecutiveProfile]]></Obj>
<Details plainTxt="False" ><![CDATA[PbWindow]]></Details>
<Time><![CDATA[4/29/2015 - 0:07:19]]></Time>
<TimeTick>1430291239</TimeTick>
<Step rID="T43">
<Obj plainTxt="False" ><![CDATA[Pb_dtwdwAccountExecutiveProfile2.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[4/29/2015 - 0:07:19]]></Time>
<TimeTick>1430291239</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="83" >
<Disp><![CDATA[Pb_dtwdwAccountExecutiveProfile2.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T44">
<Obj plainTxt="False" ><![CDATA[Pb_dtwdwAccountExecutiveProfile2.GetCellData]]></Obj>
<Details plainTxt="False" ><![CDATA["#2", "acct_exec_id", "163"]]></Details>
<Time><![CDATA[4/29/2015 - 0:07:19]]></Time>
<TimeTick>1430291239</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="85" >
<Di